### ISSUE TITLE
Exemplo de Consulta

### ISSUE THREAD

**Issue by franklingoncalves** [AndreLuisCelestino/CleanArchitectureDelphi#1]
André, você consegue expandir o exemplo mostrando como seria feito uma consulta, por exemplo, retorno o saldo atual. Só para exemplificar como fazer o retorno de dados da entidade para a view seguindo os padrões do Clean Architecture.

**Comment by AndreLuisCelestino** [comment]
Olá, @franklingoncalves!
Opa, claro. Vou implementar esse exemplo e subir aqui em breve.
Obrigado!

**Comment by AndreLuisCelestino** [comment]
O projeto de exemplo foi enviado ao autor da _Issue_. Decidi não subir essa alteração no GitHub para não divergir do que foi apresentado na Embarcadero Conference.
